#!/bin/sh
#
# Removes the garbage image variants generated by an older version of
# optimize_images.php, which reprocessed its own output (name-thumb.webp,
# name-400w.jpg, ...) as if it were a fresh source image. A file is
# considered garbage if its name (without extension) contains two or more
# of the "-thumb" / "-<width>w" suffixes, e.g. name-thumb-thumb.webp or
# name-800w-400w-thumb.webp. A real original or a single legitimate
# variant only ever has at most one such suffix, so this never touches
# anything else.
#
# Usage:
#   ./cleanup_image_variants.sh [directory]           # dry run, lists matches
#   ./cleanup_image_variants.sh [directory] --force    # actually deletes them

set -eu

dir="${1:-$(dirname "$0")/../public/img}"
force=0
for arg in "$@"; do
    [ "$arg" = "--force" ] && force=1
done

if [ ! -d "$dir" ]; then
    echo "Directory not found: $dir" >&2
    exit 1
fi

count=0
while IFS= read -r file; do
    base=$(basename "$file")
    stem="${base%.*}"
    hits=$(printf '%s' "$stem" | grep -oE -- '-([0-9]+w|thumb)' | wc -l)
    if [ "$hits" -ge 2 ]; then
        count=$((count + 1))
        if [ "$force" -eq 1 ]; then
            rm -f -- "$file"
            echo "removed: $file"
        else
            echo "would remove: $file"
        fi
    fi
done <<EOF
$(find "$dir" -maxdepth 1 -type f)
EOF

echo ""
if [ "$force" -eq 1 ]; then
    echo "Removed $count garbage variant(s) from $dir"
else
    echo "$count garbage variant(s) found in $dir (dry run - re-run with --force to delete)"
fi
